import { Memory } from "../../types";

export const PRINT_TEST_MEMORIES: Memory[] = [
  {
    id: "mem-test-001",
    userId: "usr-admin-01",
    title: "اعتماد البروتوكول المالي والاستثماري لتحديث التغذية الراجعة المؤسسية",
    description: `تم إجراء تقييم شامل لكافة آليات تدفق المعلومات المالية والتحليلية بين الإدارات التنفيذية والقطاعات التشغيلية. تبيّن أن البطء في اتخاذ القرارات الاستثمارية كان ناتجاً عن تشتت مصادر البيانات وعدم الاعتماد على سجل توثيقي سببي موحد.

يتطلب هذا التوجيه إلزام كافة رؤساء القطاعات بتقديم تقارير التوثيق السببي اليومية واستخدام آليات التحليل المعززة بخوارزميات ذكاء الأعمال المعتمدة في المنظومة.`,
    category: "Financial Strategy",
    riskLevel: "Critical",
    causalFactors: "عدم تجانس منظومة تجميع البيانات، وجود فجوات في التنسيق البيني بين قسم المحاسبة وإدارة المخاطر، والاعتماد على جداول بيانات تقليدية غير مدمجة.",
    decision: "المصادقة الفورية على تدشين منصة الذكاء المؤسسي الموحدة ZAKIR وتفعيل بروتوكول المصادقة المزدوجة على كافة التقارير السيادية قبل نهاية الربع الحالي.",
    outcomes: "تقليص زمن معالجة المخاطر بنسبة 45٪، وتحسين سرعة استجابة المجلس التنفيذي للتقلبات المالية الطارئة خلال 24 ساعة.",
    lessonsLearned: "إن التوثيق المؤسسي ليس مجرد أرشفة سكونية، بل هو أداة حية تمنع تكرار الأخطاء الاستراتيجية وتضمن التراكم المعرفي التراكمي للإدارة العليا.",
    authorName: "د. عبد الله المنصوري",
    authorEmail: "a.almansoori@zakir.gov.sa",
    authorRole: "CEO",
    createdAt: "2026-08-20T10:30:00Z",
    tags: ["Financial", "Governance", "Risk-Management", "Strategy"],
  },
  {
    id: "mem-test-002",
    userId: "usr-admin-02",
    title: "Global Supply Chain Infrastructure Optimization & Vendor Governance Audit",
    description: `During the comprehensive Q3 logistics review, critical vulnerabilities were identified across key maritime supply lines serving Western Africa and the Mediterranean hub. Unforeseen port delays and escalating demurrage charges led to a 14.2% operational cost spike.

This decision document establishes a unified vendor scoring framework, real-time container tracking telemetry integration, and mandatory fallback routing logic for all high-value shipments exceeding $500,000 USD.`,
    category: "Operations & Logistics",
    riskLevel: "High",
    causalFactors: "Single-point-of-failure reliance on primary transshipment terminals, insufficient predictive ETA tracking, and delayed escalation during custom inspections.",
    decision: "Mandate dual-sourcing strategy for all critical logistics contracts, integrate IoT container telemetry with Zakir Risk Radar, and execute revised SLAs with 72-hour maximum resolution caps.",
    outcomes: "Eliminated $1.2M in potential demurrage penalties within the first 60 days of implementation. Average logistics chain transparency index increased from 62% to 94%.",
    lessonsLearned: "Never permit primary logistics operations to function without a hot-standby secondary carrier framework. Real-time causal visibility directly prevents multi-million dollar supply bottlenecks.",
    authorName: "Sarah Jenkins, VP of Supply Chain Operations",
    authorEmail: "s.jenkins@enterprise-zakir.com",
    authorRole: "Admin",
    createdAt: "2026-08-21T14:15:00Z",
    tags: ["Logistics", "SupplyChain", "VendorManagement", "Audit"],
  },
  {
    id: "mem-test-003",
    userId: "usr-admin-03",
    title: "Audit d'Architecture de Sécurité Cloud et Conformité Réglementaire RGPD",
    description: `À la suite de la directive européenne sur la protection des données sensibles et des infrastructures stratégiques, un audit approfondi des systèmes de stockage et de transmission des données a été mené sur l'ensemble du réseau d'entreprise.

L'analyse a révélé la nécessité de renforcer le chiffrement des données au repos et d'appliquer une segmentation stricte des environnements de développement et de production afin d'éliminer toute possibilité d'exposition accidentelle.`,
    category: "Cybersecurity & Compliance",
    riskLevel: "Critical",
    causalFactors: "Absence d'un registre centralisé d'accès aux clés de chiffrement KMS, persistance de jetons d'accès obsolètes dans certains microservices patrimoniaux.",
    decision: "Mise en œuvre immédiate de l'architecture Zero-Trust avec rotation automatique des clés d'API toutes les 24 heures et audit continu via le moteur de conformité Zakir.",
    outcomes: "Obtention de la certification ISO/IEC 27001 avec un score parfait. Suppression intégrale des vecteurs de vulnérabilité identifiés.",
    lessonsLearned: "La sécurité des données ne doit jamais être considérée comme une étape finale, mais comme une exigence fondamentale intégrée dès la conception initiale de chaque infrastructure.",
    authorName: "Jean-Luc Picard, Directeur de la Sécurité des Systèmes d'Information",
    authorEmail: "jl.picard@zakir.eu",
    authorRole: "Compliance Officer",
    createdAt: "2026-08-22T09:00:00Z",
    tags: ["Cybersecurity", "GDPR", "ZeroTrust", "Compliance"],
  },
  {
    id: "mem-test-004",
    userId: "usr-admin-04",
    title: "تحديث البنية التحتية للخوادم والتحول الشامل لنظام التشغيل السحابي الذاتي",
    description: `في إطار خطة التحول الرقمي الوطنية واستدامة الخدمات الموجهة للمواطنين والمؤسسات، تم إنجاز مرحلة نقل مركز البيانات الرئيسي إلى النظام السحابي الهجين الموزع.

شملت العملية أكثر من 120 خادماً فيزيائياً وتمت معالجة نقل أكثر من 450 تيرابايت من البيانات الحساسة دون تسجيل أي انقطاع في مستوى الخدمة أو تراجع في الأداء.`,
    category: "Cloud Engineering",
    riskLevel: "Medium",
    causalFactors: "تقادم الأجهزة الصلبة السابقة، ارتفاع تكاليف الصيانة الدورية، والحاجة إلى سعة معالجة مرنة تتكيف مع ساعات الذروة.",
    decision: "الموافقة الكاملة على إيقاف تشغيل مركز البيانات القديم والاعتماد الحصري على البنية التحتية السحابية الموزعة المعززة بخوادم الأمان الفائق.",
    outcomes: "خفض تكاليف الطاقة والصيانة بنسبة 38٪، وزيادة وقت الجاهزية التشغيلية (Uptime) إلى 99.999٪.",
    lessonsLearned: "التخطيط المحكم وااختبار سيناريوهات الكوارث قبل النقل الفعلي يضمن الانتقال السلس بدون التأثير على استمرارية الأعمال.",
    authorName: "م. طارق العتيبي",
    authorEmail: "t.otaibi@zakir.gov.sa",
    authorRole: "Analyst",
    createdAt: "2026-08-23T11:45:00Z",
    tags: ["Cloud", "Infrastructure", "Migration", "DevOps"],
  },
  {
    id: "mem-test-005",
    userId: "usr-admin-05",
    title: "Enterprise Artificial Intelligence Policy & Ethical Governance Framework",
    description: `As synthetic media, generative intelligence models, and autonomous reasoning agents become deeply embedded within daily corporate workflows, the Governance Board has mandated the immediate release of the Enterprise AI Ethics Directive.

This policy delineates strict boundaries regarding proprietary source code input, customer data anonymization, human-in-the-loop signoff mandates for financial approvals, and explicit logging of all AI-assisted strategic analyses.`,
    category: "AI Governance",
    riskLevel: "High",
    causalFactors: "Rapid adoption of unsanctioned third-party AI tools across internal engineering teams without prior threat modeling or legal counsel clearance.",
    decision: "Deploy private enterprise-only Gemini & Antigravity proxy endpoints, strictly ban unencrypted external LLM usage, and require automated logging of all decision artifacts in Zakir Vault.",
    outcomes: "Zero data leakage incidents recorded. 100% compliance across all 1,400 software engineers and strategy analysts within 30 days.",
    lessonsLearned: "Proactive, clear ethical guidelines encourage safe innovation rather than suppressing technological adoption.",
    authorName: "Dr. Elena Rostova, Chief AI Ethics Officer",
    authorEmail: "elena.rostova@zakir-ai.org",
    authorRole: "Risk Auditor",
    createdAt: "2026-08-24T16:20:00Z",
    tags: ["AIGovernance", "Ethics", "Policy", "Compliance"],
  },
  {
    id: "mem-test-006",
    userId: "usr-admin-06",
    title: "إعادة هيكلة إدارة الأزمات والتحجيم التلقائي للمصادر أثناء الطوارئ",
    description: `حرصاً على استجابة المنظمة للأزمات الإقليمية والمناخية والتشغيلية، تم تطوير وتطبيق خطة الطوارئ المعتمدة على محاكاة المحركات السبببة لنظام Zakir.

تتضمن الخطة تفعيلاً تلقائياً لفرق العمل المستقلة، وتحويل الصلاحيات التنفيذية وفق مصفوفة التفويض المعتمدة عند تجاوز مؤشرات الخطر للعتبة الحرجة.`,
    category: "Crisis Management",
    riskLevel: "Critical",
    causalFactors: "تأخر الاستجابة خلال أزمة سلاسل الإمداد العالمية لعام 2024 بسبب بيروقراطية اتخاذ القرار وتعدد سلاسل المراجعة.",
    decision: "تطبيق مصفوفة الاستجابة السريعة وتفويض رؤساء اللجان الفرعية بصلاحية إنفاق طارئ حتى 500,000 ريال دون الحاجة لاجتماع المجلس عند إعلان حالة الخطر البرتقالي.",
    outcomes: "سرعة استجابة فائقة وتقليص زمن التفعيل من 48 ساعة إلى 15 دقيقة فقط.",
    lessonsLearned: "المرونة الهيكلية ووضوح التفويض هما الحصن الحقيقي للمؤسسات في مواجهة الاضطرابات المفاجئة.",
    authorName: "سعادة اللواء م. خالد الشمري",
    authorEmail: "k.alshammari@zakir.gov.sa",
    authorRole: "Admin",
    createdAt: "2026-08-25T08:00:00Z",
    tags: ["CrisisManagement", "Emergency", "Governance", "Resilience"],
  },
];
