import http from "http";

interface TestCheckResult {
  testId: string;
  category: string;
  prompt: string;
  passed: boolean;
  httpStatus: number;
  intent: string;
  hasCohesiveAnswer: boolean;
  noTechnicalErrors: boolean;
  noRoboticBoilerplate: boolean;
  noEmojis: boolean;
  proportionalConfidence: boolean;
  sampleResponse: string;
  failureReasons: string[];
}

function makeAgentChatRequest(
  body: any,
  headers: Record<string, string> = {}
): Promise<{ status: number; data: any }> {
  return new Promise((resolve, reject) => {
    const postData = JSON.stringify(body);
    const req = http.request(
      {
        host: "127.0.0.1",
        port: 3000,
        path: "/api/agent/chat",
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Content-Length": Buffer.byteLength(postData),
          ...headers,
        },
      },
      (res) => {
        let raw = "";
        res.on("data", (chunk) => (raw += chunk));
        res.on("end", () => {
          let data: any = {};
          try {
            data = JSON.parse(raw);
          } catch (e) {
            data = { rawText: raw };
          }
          resolve({ status: res.statusCode || 500, data });
        });
      }
    );

    req.on("error", (err) => reject(err));
    req.write(postData);
    req.end();
  });
}

function validateResponseQuality(
  text: string,
  isUnauthenticatedPrivateQuery: boolean = false
): {
  hasCohesiveAnswer: boolean;
  noTechnicalErrors: boolean;
  noRoboticBoilerplate: boolean;
  noEmojis: boolean;
  proportionalConfidence: boolean;
  failureReasons: string[];
} {
  const failureReasons: string[] = [];
  const raw = text || "";
  const lower = raw.toLowerCase();

  // 1. Non-empty & minimum length
  if (!raw.trim() || raw.trim().length < 15) {
    failureReasons.push("Response is empty or shorter than 15 characters");
  }

  // 2. Technical error leakage check
  const badTechWords = [
    "401", "403", "404", "500", "cors", "unauthorized", "forbidden",
    "api route not found", "stack trace", "resource_exhausted", "internal server error"
  ];
  const hasTechError = badTechWords.some((w) => lower.includes(w));
  if (hasTechError) {
    failureReasons.push("Contains technical error jargon or status codes");
  }

  // 3. Robotic Boilerplate check
  const roboticPatterns = [
    "بالنسبة لاستفسارك حول",
    "تعتمد إدارة الأعمال الحديثة على مواءمة الأهداف الاستراتيجية مع المؤشرات التشغيلية والرقابة المستمرة.",
    "🚨 تحليل خطير جداً",
    "generated by ai",
    "ai analysis",
    "system detected",
    "technical diagnosis"
  ];
  const hasRoboticBoilerplate = roboticPatterns.some((p) => raw.includes(p));
  if (hasRoboticBoilerplate) {
    failureReasons.push("Contains canned robotic boilerplate or prohibited AI tags");
  }

  // 4. Zero Emojis check
  const emojiRegex = /[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]|[\u{1F600}-\u{1F64F}]|[\u{1F680}-\u{1F6FF}]|[\u{1F1E6}-\u{1F1FF}]|⭐|🚀|💡|⚠️|🔥|✅|❌|📊|🤖|🎯|📌|🔹|🔸|⚡|✨|🛡️|🚨/gu;
  const hasEmojis = emojiRegex.test(raw);
  if (hasEmojis) {
    failureReasons.push("Contains prohibited emojis or decorative icons");
  }

  // 5. Proportional Confidence check (no premature definitive claims without evidence)
  const falseCertaintyPatterns = [
    "الشركة ستنهار حتماً",
    "فشل مالي مؤكد",
    "ستفلس الأسبوع القادم",
    "المؤسسة تعاني من ضعف مالي شامل"
  ];
  const hasFalseCertainty = falseCertaintyPatterns.some((p) => raw.includes(p));
  if (hasFalseCertainty) {
    failureReasons.push("Contains premature definitive claims without empirical evidence");
  }

  // 6. Cohesive answer check (no scattered repeated paragraphs)
  const lines = raw.split("\n").map((l) => l.trim()).filter(Boolean);
  const duplicates = lines.filter((item, index) => lines.indexOf(item) !== index && item.length > 25);
  if (duplicates.length > 0) {
    failureReasons.push("Contains verbatim duplicate paragraphs");
  }

  return {
    hasCohesiveAnswer: raw.trim().length >= 15 && duplicates.length === 0,
    noTechnicalErrors: !hasTechError,
    noRoboticBoilerplate: !hasRoboticBoilerplate,
    noEmojis: !hasEmojis,
    proportionalConfidence: !hasFalseCertainty,
    failureReasons,
  };
}

async function runQualitySuite() {
  console.log("\n================================================================================");
  console.log("COGNITIVE ADVISOR 16-POINT COMPREHENSIVE QUALITY & REASONING SUITE");
  console.log("================================================================ drop-16\n");

  const testCases = [
    {
      id: "Q01",
      category: "1. سؤال عام",
      prompt: "أهلاً ومرحباً بك، صباح الخير",
      history: [],
      auth: false,
      expectKeywords: ["أهلاً", "المستشار", "خدمتك"],
    },
    {
      id: "Q02",
      category: "2. سؤال إداري",
      prompt: "كيف يمكنني مواءمة الأهداف الإدارية مع فرق العمل القيادية؟",
      history: [],
      auth: false,
      expectKeywords: ["الأهداف", "مؤشرات", "القيادة"],
    },
    {
      id: "Q03",
      category: "3. سؤال مالي",
      prompt: "ما هو التدفق النقدي؟ وكيف يؤثر على السيولة النقدية للشركة؟",
      history: [],
      auth: false,
      expectKeywords: ["التدفق النقدي", "السيولة", "الالتزامات"],
    },
    {
      id: "Q04",
      category: "4. سؤال عن المخاطر",
      prompt: "كيف نتعامل مع مخاطر تقلبات أسعار الصرف في العقود الدولية؟",
      history: [],
      auth: false,
      expectKeywords: ["المخاطر", "التحوط", "انكشاف"],
    },
    {
      id: "Q05",
      category: "5. طلب تشخيص",
      prompt: "شخص لي مشكلة الفجوة بين حجم المبيعات المرتفع وضغط السيولة الحاد.",
      history: [],
      auth: false,
      expectKeywords: ["الخلاصة", "التشخيص", "الأدلة", "التوصية"],
    },
    {
      id: "Q06",
      category: "6. طلب تقرير",
      prompt: "أعد لي تقريراً تنفذياً حول إدارة رأس المال العامل ودورة التحصيل.",
      history: [],
      auth: false,
      expectKeywords: ["الخلاصة", "التشخيص", "التوصية"],
    },
    {
      id: "Q07",
      category: "7. طلب توصية",
      prompt: "ما هي التوصية الاستراتيجية الأنسب قبل فتح فرع جديد للمؤسسة؟",
      history: [],
      auth: false,
      expectKeywords: ["التوصية", "الجدوى", "السيولة"],
    },
    {
      id: "Q08",
      category: "8. سؤال غامض",
      prompt: "اشرح لي هذا",
      history: [],
      auth: false,
      expectKeywords: ["توضيح", "القرار", "المسألة"],
    },
    {
      id: "Q09",
      category: "9. سؤال يحتاج سياق المحادثة",
      prompt: "وماذا أفعل؟",
      history: [
        { role: "user", text: "لدينا مشكلة حادة في السيولة بسبب تأخر تحصيل الذمم المدينة." },
        { role: "model", text: "تأخر التحصيل يسبب فجوة نقدية دورية بين الإيرادات والدفعات." },
      ],
      auth: false,
      expectKeywords: ["السيولة", "التحصيل", "الالتزامات"],
    },
    {
      id: "Q10",
      category: "10. سؤال يعتمد على بيانات المؤسسة",
      prompt: "الذكريات المسجلة في حسابي",
      history: [],
      auth: true,
      memories: [{ title: "قرار زيادة رأس المال", category: "Finance", decision: "الموافقة" }],
      expectKeywords: ["الذاكرة المؤسسية", "قرار زيادة رأس المال"],
    },
    {
      id: "Q11",
      category: "11. سؤال مع بيانات غير كافية",
      prompt: "حلل وضعي المالي بناءً على البيانات الموجودة",
      history: [],
      auth: false,
      expectKeywords: ["المعطيات", "لا تكفي", "إطار"],
    },
    {
      id: "Q12",
      category: "12. فرضية غير مؤكدة",
      prompt: "شركتنا تعاني من ضعف مالي شامل وستفلس الأسبوع القادم لا محالة.",
      history: [],
      auth: false,
      expectKeywords: ["لا تكفي وحدها", "مؤشرات", "قبل الحكم"],
    },
    {
      id: "Q13",
      category: "13. سؤال لا يحتاج بيانات خاصة",
      prompt: "ما هي مبادئ حوكمة الشركات الإدارية؟",
      history: [],
      auth: false,
      expectKeywords: ["الحوكمة", "شفافية", "مساءلة"],
    },
    {
      id: "Q14",
      category: "14. سؤال غير متوقع",
      prompt: "هل ننفتح على خط إنتاج جديد مخصص للتصدير؟",
      history: [],
      auth: false,
      expectKeywords: ["خط إنتاج", "تصدير", "الجدوى"],
    },
    {
      id: "Q15",
      category: "15. رسالة قصيرة جداً",
      prompt: "حلل",
      history: [],
      auth: false,
      expectKeywords: ["مساعدتك", "توضيح", "المسألة"],
    },
    {
      id: "Q16",
      category: "16. متابعة لسؤال سابق",
      prompt: "ما الخطوة التالية؟",
      history: [
        { role: "user", text: "لدي اجتماع قريب جداً مع مستثمر رئيسي للتفاوض حول الجولة." },
        { role: "model", text: "التحضير للمستثمر يستوجب تجهيز اقتصاديات الوحدة والمدرج النقدي." },
      ],
      auth: false,
      expectKeywords: ["مستثمر", "الخطوة التالية", "النقدي"],
    },
  ];

  const results: TestCheckResult[] = [];

  for (const tc of testCases) {
    try {
      const headers: Record<string, string> = {};
      if (tc.auth) {
        headers["Authorization"] = "Bearer mock_token_admin";
      }

      const res = await makeAgentChatRequest(
        {
          prompt: tc.prompt,
          history: tc.history || [],
          memories: tc.memories || [],
          lang: "ar",
        },
        headers
      );

      const responseText = res.data.text || res.data.response || "";
      const quality = validateResponseQuality(responseText, tc.auth && !tc.auth);
      const isHttp200 = res.status === 200;

      // Check keywords relevance
      const lowerResp = responseText.toLowerCase();
      const missingKeywords = tc.expectKeywords.filter((kw) => !lowerResp.includes(kw.toLowerCase()));
      if (missingKeywords.length > 0) {
        quality.failureReasons.push(`Missing expected contextual keywords: [${missingKeywords.join(", ")}]`);
      }

      const passed = isHttp200 && quality.failureReasons.length === 0;

      results.push({
        testId: tc.id,
        category: tc.category,
        prompt: tc.prompt,
        passed,
        httpStatus: res.status,
        intent: res.data.intent || "UNKNOWN",
        hasCohesiveAnswer: quality.hasCohesiveAnswer,
        noTechnicalErrors: quality.noTechnicalErrors,
        noRoboticBoilerplate: quality.noRoboticBoilerplate,
        noEmojis: quality.noEmojis,
        proportionalConfidence: quality.proportionalConfidence,
        sampleResponse: responseText.substring(0, 100).replace(/\n/g, " "),
        failureReasons: quality.failureReasons,
      });
    } catch (err: any) {
      results.push({
        testId: tc.id,
        category: tc.category,
        prompt: tc.prompt,
        passed: false,
        httpStatus: 500,
        intent: "ERROR",
        hasCohesiveAnswer: false,
        noTechnicalErrors: false,
        noRoboticBoilerplate: false,
        noEmojis: false,
        proportionalConfidence: false,
        sampleResponse: err.message,
        failureReasons: [`Network request failed: ${err.message}`],
      });
    }
  }

  console.log("--------------------------------------------------------------------------------");
  results.forEach((r) => {
    const icon = r.passed ? "✅" : "❌";
    console.log(`${icon} [${r.testId}] ${r.category}: ${r.passed ? "PASS" : "FAIL"} (HTTP ${r.httpStatus}, Intent: ${r.intent})`);
    console.log(`   Prompt: "${r.prompt}"`);
    console.log(`   Sample: "${r.sampleResponse}..."`);
    if (r.failureReasons.length > 0) {
      console.log(`   ⚠️ Failure Reasons: ${r.failureReasons.join(" | ")}`);
    }
    console.log("");
  });

  console.log("================================================================================");
  const totalPassed = results.filter((r) => r.passed).length;
  console.log(`QUALITY SUITE SUMMARY: TOTAL: ${results.length} | PASSED: ${totalPassed} | FAILED: ${results.length - totalPassed}`);
  console.log("================================================================================\n");

  if (totalPassed === results.length) {
    console.log("🎉 ALL 16 QUALITY & REASONING SUITE TESTS PASSED 100%!");
    process.exit(0);
  } else {
    console.error("⚠️ SOME QUALITY SUITE TESTS FAILED");
    process.exit(1);
  }
}

runQualitySuite().catch((e) => {
  console.error("FATAL ERROR IN QUALITY SUITE:", e);
  process.exit(1);
});
