process.env.SKIP_SERVER_LISTEN = "true";
process.env.VERCEL = "1";

import type { IncomingMessage, ServerResponse } from "http";

let cachedApp: any = null;

async function getApp() {
  if (cachedApp) return cachedApp;
  try {
    // Try bundled server output first (generated by npm run build)
    const distMod = await import("../dist/server.cjs" as any);
    cachedApp = distMod.default?.default || distMod.default || distMod;
    if (typeof cachedApp === "function") return cachedApp;
  } catch (e) {
    // Fallback if dist/server.cjs is not yet generated
  }

  try {
    const srcMod = await import("../server" as any);
    cachedApp = srcMod.default?.default || srcMod.default || srcMod;
    return cachedApp;
  } catch (err) {
    console.error("[Vercel API Handler] Error loading server module:", err);
    throw err;
  }
}

export default async function handler(req: IncomingMessage, res: ServerResponse) {
  try {
    const expressApp = await getApp();
    if (typeof expressApp === "function") {
      return expressApp(req, res);
    }
    throw new Error("Express application handler is not a callable function");
  } catch (err: any) {
    console.error("[Vercel Serverless Invocation Exception]", err);
    if (!res.headersSent) {
      res.setHeader("Content-Type", "application/json");
      res.statusCode = 500;
      res.end(JSON.stringify({
        success: false,
        error: "SERVERLESS_INVOCATION_ERROR",
        message: err?.message || "Internal serverless function error"
      }));
    }
  }
}



